services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: 8082
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 8082
    ports:
      - "8080:80"
    depends_on:
      - postgres