export const FILE_UPLOAD_URL = "http://localhost:8000/files/upload"
export const JWT_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1IiwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQwMTM3MjY5fQ._YlPx-pYZaUzQC6sfNdHTIPqLE4Oldd9fC6BtHDi__0"
